### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ghost** [Jay-ArBrouillard/jay-bit-hash#1]
Edit: Im able to run main script but however nothing is happening no terminal no nothing but cmd script is running.

**Comment by esegovicDev37** [comment]
Windows exe file isnt working either. Just open close window. Maybe duo lacking of docus how to run it up.

**Comment by Jay-ArBrouillard** [comment]
Hi,

I just tried cloning from scratch, creating virtualenv, installing dependencies, and then running it.

Can you try expanding your terminal screen to see output? Perhaps you can provide more information.

Thanks,

Jay-Ar

**Comment by ghost** [comment]
Hello. Im windows user. I installed all depends edited a path to run it where is located. Oncei run main.py its only blackscreen on my cmd. There is no terminal.

**Comment by Jay-ArBrouillard** [comment]
The terminal is the command prompt. Also are on Python 3.6.3 or higher? The Rich library is dependent on that.

Can you try starting from the beginning (starting from cloning the repository and creating your own virtual environment) and send some screenshots of your terminal output. Otherwise, it is hard for me to help you.

**Comment by ghost** [comment]
ERROR: No matching distribution found for selenium==4.1.3
"selenium" last version 4.0.0a7

ERROR: No matching distribution found for trio==0.20.0

"trio" last version is 0.19.0

wsproto==1.1.0

Last version of it is 1.0.0

**Comment by Jay-ArBrouillard** [comment]
Selenium 4.1.3 and trio 0.20.0 are valid versions.

See https://pypi.org/project/selenium/ and https://pypi.org/project/trio/

I suggest just try reinstall or manually install selenium and trio with pip if nothing else works.
pip install selenium
pip install trio

I am going to close this issue as you had posted another issue implying you had got this running.
