### ISSUE TITLE
Max Hashes

### ISSUE THREAD

**Issue by ghost** [Jay-ArBrouillard/jay-bit-hash#2]
Hello. I lowered number like  for  Exec. Max. Hashes per thread to 500 only for test purposes and it seems that he is doing same hashes per min/hour.

Is this possible. Running for 2Hours straight.

**Comment by Jay-ArBrouillard** [comment]
The max hashes per thread is how many times SHA256 is executed for each hash. So in short yes, a change of a couple thousand won't make a significant difference in hashes per min/hour. Now if you went from max hashes of like 50,000 to 500, then you should notice some difference in hashes per min/hour.

**Comment by ghost** [comment]
Im running 2+ Days right now with 180k per hour. How long could it take to catch hash?

**Comment by Jay-ArBrouillard** [comment]
To be clear, the method of testing hashes here is completely random and the number of possible hashes is 2^256. This program will likely never find a winning hash, but it is possible. Also we cannot simply brute force the answer even with all the processing power in the world. At the end of the day I would not try to fry your PC by running this program for days on end. I personally only run this for 2-8 hours most days.
